#
# Module manifest for module 'WinSCP'
#
# Generated by: Thomas J. Malkewitz @dotps1
#
# Generated on: 9/5/2015
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'WinSCP'

# Version number of this module.
ModuleVersion = '5.7.5.9'

# ID used to uniquely identify this module
GUID = '06e0af4e-779b-48f4-939f-c90b8ec950e6'

# Author of this module
Author = 'Thomas J. Malkewitz @dotps1'

# Company or vendor of this module
# CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) 2015 Thomas J. Malkewitz @dotps1. All rights reserved.  Licensed with GNU GENERAL PUBLIC LICENSE.'

# Description of the functionality provided by this module
Description = 'PowerShell Module Wrapper for WinSCP.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '4.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
DotNetFrameworkVersion = '4.5'

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @(
    'NeededAssemblies\WinSCPNet.dll'
)

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @(
    'WinSCP.format.ps1xml'
)

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
    FunctionsToExport = 'ConvertTo-WinSCPEscapedString',
                        'Get-WinSCPChildItem',
                        'Get-WinSCPItem',
                        'Get-WinSCPItemChecksum',
                        'Invoke-WinSCPCommand',
                        'Move-WinSCPItem',
                        'New-WinSCPItem',
                        'New-WinSCPItemPermission',
                        'New-WinSCPSession',
                        'New-WinSCPTransferOption',
                        'Receive-WinSCPItem',
                        'Remove-WinSCPItem',
                        'Remove-WinSCPSession',
                        'Rename-WinSCPItem',
                        'Send-WinSCPItem',
                        'Start-WinSCPConsole',
                        'Sync-WinSCPPath',
                        'Test-WinSCPPath'

# Cmdlets to export from this module
# CmdletsToExport = '*'

# Variables to export from this module
# VariablesToExport = '*'

# Aliases to export from this module
# AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @(
    'LICENSE.md',
    'README.md',
    'WinSCP.format.ps1xml',
    'WinSCP.psd1',
    'WinSCP.psm1',
    'en-US\about_WinSCP.help.txt',
    'en-US\WinSCP-Help.xml'
    'Functions\_Helper.Format-WinSCPPathString.ps1',
    'Functions\ConvertTo-WinSCPEscapedString.ps1',
    'Functions\Get-WinSCPChildItem.ps1',
    'Functions\Get-WinSCPFileChecksum.ps1',
    'Functions\Invoke-WinSCPCommand.ps1',
    'Functions\Move-WinSCPItem.ps1',
    'Functions\New-WinSCPItemPermission.ps1'
    'Functions\New-WinSCPItem.ps1',
    'Functions\New-WinSCPTransferOption.ps1',
    'Functions\New-WinSCPSession.ps1',
    'Functions\Receive-WinSCPItem.ps1',
    'Functions\Remove-WinSCPItem.ps1',
    'Functions\Remove-WinSCPSession.ps1',
    'Functions\Rename-WinSCPItem.ps1',
    'Functions\Send-WinSCPItem.ps1',
    'Functions\Start-WinSCPConsole.ps1',
    'Functions\Sync-WinSCPDirectory.ps1',
    'Functions\Test-WinSCPPath.ps1',
    'NeededAssemblies\license.txt',
    'NeededAssemblies\license-dotnet.txt',
    'NeededAssemblies\readme.txt',
    'NeededAssemblies\readme_automation.txt',
    'NeededAssemblies\WinSCP.exe',
    'NeededAssemblies\WinSCPnet.dll'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @(
            'Ftp'
            'Sftp'
            'WinSCP'
        )

        # A URL to the license for this module.
        LicenseUri = 'https://raw.githubusercontent.com/dotps1/WinSCP/master/LICENSE.md'

        # A URL to the main website for this project.
        ProjectUri = 'http://dotps1.github.io/WinSCP'

        # A URL to an icon representing this module.
        IconUri = 'http://winscp.net/eng/images/og_logo_240x240.jpg'

        # ReleaseNotes of this module
        ReleaseNotes = 'Added support for full and relitive paths: https://github.com/dotps1/WinSCP/issues/25'

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'https://raw.githubusercontent.com/dotps1/WinSCP/master/en-US/WinSCP-Help.xml'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = 'WinSCP'

}